### PR TITLE
Avoid TypeError in phase_cross_correlation with disambiguate=True

### LINKED ISSUE #7089: phase_cross_correlation with disambiguate=True can fail with TypeError: 'NoneType' object is not iterable
### Description:

`phase_cross_correlation` with `disambiguate=True` can fails with `TypeError: 'NoneType' object is not iterable`.

For example this happens if one of the images is empty.

### Way to reproduce:

```python
import numpy as np
import skimage as ski

im = np.random.randint(0, 100, ((10,10)))

ski.registration.phase_cross_correlation(im, im * 0, disambiguate=True)
```

```
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    ski.registration.phase_cross_correlation(im, im*0, disambiguate=True)
  File "C:\Python311\Lib\site-packages\skimage\registration\_phase_cross_correlation.py", line 401, in phase_cross_correlation
    shift = _disambiguate_shift(reference_image, moving_image, shift)
  File "C:\Python311\Lib\site-packages\skimage\registration\_phase_cross_correlation.py", line 171, in _disambiguate_shift
    for sl, pos_shift, neg_shift in zip(
TypeError: 'NoneType' object is not iterable
```

### Version information:

```Shell
3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
scikit-image version: 0.21.0
numpy version: 1.24.3
```
```

### PR DESCRIPTION
**Pull request by petsuter**
## Description

Fixes #7089.

## Checklist

- A descriptive but concise pull request title
- [Docstrings for all functions](https://github.com/numpy/numpy/blob/master/doc/example.py)
- [Unit tests](https://scikit-image.org/docs/dev/development/contribute.html#testing)
- A gallery example in `./doc/examples` for new features
- [Contribution guide](https://scikit-image.org/docs/dev/development/contribute.html) is followed

## Release note

Summarize the introduced changes in the code block below in one or a few sentences. The
summary will be included in the next release notes automatically:

```release-note
Fixed TypeError in phase_cross_correlation with disambiguate=True
```

### CODE REVIEW

**Comment by petsuter** [comment]
@lagru Is there anything more needed here? Thanks.

**Comment by lagru** [comment]
Oh, hey @petsuter. I never saw this PR because you made it against the `main` branch of your own fork and not against scikit-image. Instead you should be able to [follow this link](https://github.com/scikit-image/scikit-image/compare/main...petsuter:scikit-image:issue-7089) to make a PR against `scikit-image:main` proper. Please feel welcome to reach out if you need help or a review as soon as you want. :)

**Comment by petsuter** [comment]
Ah, oops. Thanks.

**Comment by petsuter** [comment]
https://github.com/scikit-image/scikit-image/pull/7259

**Pull request closed without merging**
